#!/bin/bash
#Test ob pushen und pullen auf Halo funktioniert
#####################################################################
#Flag fuer das Ausgeben des Hilfe Textfiles
#####################################################################

while getopts "ah" OPTION
do
    case $OPTION in
    h)
 	help_pfad=$(dirname $0)
	vim "$help_pfad/help_conformere_org.txt" 
        exit
        ;;
#####################################################################
#Wenn Flag a gewaehlt wurde, erstellt das Skript von jeder Datei einen
#Ordner mit demselben Namen und verschiebt sie darein
#####################################################################
    a)
for file in *; 
do

leer=$(find -maxdepth 1 -type f)

if [[ -z $leer ]]; then
	echo -e "\e[31mNo files in this folder. Aborting.\e[39m"
	exit
fi 

if [ -d $file ]; then
	continue
fi	

dateiendung=$(echo $file | grep -o -E "(.xyz|.dat|.gjf)\>")

if [ -z $dateiendung ]; then
	echo -e "\e[33mFile $file is not an .xyz, .dat or .gjf file.\033[0m"
	continue
fi

ordner_name=${file%.*}

if [[ -d $ordner_name ]]; then
	echo -e "\e[31mFolder $ordner_name already exists. Please check your files. Aborting.\e[39m"
	exit
fi

echo -e "File \033[1;32m$file\033[0m is moved into the new created folder \033[1;32m$ordner_name\033[0m."

mkdir $ordner_name
mv $file $ordner_name


done

exit
;;
#####################################################################
#Ende vom Code fuer Flag a
#####################################################################

    *)
	echo -e "Usage of nonexistent flag.\033[31m Aborting.\033[0m"
	exit
	;;
    esac
done 

#####################################################################
#Testen, ob der Ordner ueberhaupt Dateien enthält, wenn nicht abbruch
#####################################################################

leer=$(find -maxdepth 1 -type f)

if [[ -z $leer ]]; then
	echo -e "\e[31mNo files in this folder. Aborting.\e[39m"
	exit
fi 

#####################################################################
#Schleife über alle Element im Ordner
#####################################################################

for file in *
do

#####################################################################
#Falls es sich beim Element um einen Ordner handelt, wird die Iteration
#dieser Schleife uebersprungen
#####################################################################
if [ -d $file ]; then
	continue
fi	

#####################################################################
#"conf_number" speichert die Konformernummer der Datei
#"dateiendung" speichert die Dateiendung, falls es sich bei der Datei
#um eine xyz, dat oder gjf Datei handelt
#####################################################################	

conf_number=$(echo $file | grep -o -E "K{1}[[:digit:]]{2}")
dateiendung=$(echo $file | grep -o -E "(.xyz|.dat|.gjf)\>")

#####################################################################
#Falls es sich bei der Datei um keine xyz, dat oder gjf Datei handelt
#wird die Iteration der Schleife uebersprungen
#####################################################################
if [ -z $dateiendung ]; then
	echo -e "\e[33mFile $file is not an .xyz, .dat or .gjf file.\033[0m"
	continue
fi

#####################################################################
#Wenn der Dateiname eine Konformerenbezeichnung enthaelt, wird ein
#entsprechender Ordner erstellt und die Datei in diesen verschoben
#####################################################################
if [ -n "$conf_number" ]; then
	
#####################################################################
#Wenn ein entsprechender Ordner fuer das Konformer schon existiert,
#wird das Skript beendet
#####################################################################
	if [ -d $conf_number ]; then
		echo -e "\e[31mFolder $conf_number already exists. Please check your files. Aborting.\e[39m"
		exit
	fi

	echo -e "File \033[1;32m$file\033[0m is moved into the new created folder \033[1;32m$conf_number\033[0m."
	mkdir $conf_number
	mv $file $conf_number
else 

#####################################################################
#Falls die Datei keine Konformerenbezeichnung enthält, wird die 
#Iteration der Schleife uebersprungen
#####################################################################

	echo "File $file is not a conformere-file. Filename has to contain "K" followed by a two digit number."
fi

done
