#!/bin/bash
#
# conformer search using OpenBabel
# Syntax: getConformers [FILE]
#
#

#### initial geometry
FILE=$1
NAME=$(echo $FILE | cut -f1 -d'.')
head -1 $FILE > new-"$NAME"-file.xyz
echo "" >> new-"$NAME"-file.xyz
sed -n 3,"$"p $FILE >> new-"$NAME"-file.xyz
FILE=new-"$NAME"-file.xyz

#### number of possible conformers
TEMPFILE=temporary-"$NAME"-file.xyz
numconf=$(obabel $FILE -O $TEMPFILE --conformer | grep "Initial conformer count:" | awk '{print $NF}')
rm $TEMPFILE

#### weighted rotor search + conjugate gradient optimization
WRS="$NAME"_WRS_CG.xyz
obconformer $numconf 1000 $FILE > $WRS

CHECKLINE=1
unset PRINTERROR

while [[ $CHECKLINE -gt 0 ]]; do
        CHECKVAR=$(sed -n "$CHECKLINE"p $WRS)
        CHECKNUMCOL=$(echo "$CHECKVAR" | awk '{print NF}')
        CHECKCHAR=$(echo "$CHECKVAR" | awk '{print $1}')

	if [ "$CHECKNUMCOL" -eq 1 ] && [[ "$CHECKCHAR" =~ ^[0-9]+$ ]]; then
	        CHECKLINE=-1
	else
		PRINTERROR=$(echo $PRINTERROR $CHECKVAR)
		sed -i 1d $WRS
	fi
done

#### generate remaining conformers
obabel $WRS -O "$NAME"_conformers.xyz --conformer --nconf $numconf --score rmsd --writeconformers

prepend=$(cat $WRS)
echo "$prepend" | cat - "$NAME"_conformers.xyz > TEMP && mv TEMP "$NAME"_conformers.xyz
sed -i "2s/.*/$WRS/" "$NAME"_conformers.xyz

count=$(grep -c "$WRS" "$NAME"_conformers.xyz)
start=1
end=$(head -1 "$NAME"_conformers.xyz); end=$((end+2))
add=$end

#### assign energies (default: MMFF94; if B is present: UFF)

FORCEFIELD=MMFF94
checkatoms=$(cat $FILE | awk '{print $1}' | sort -d -u)
numcheck=$(echo "$checkatoms" | wc -l)
for (( i=1 ; i <= $numcheck ; i++))
do
	check=$(echo "$checkatoms" | sed -n "$i"p)
	if [ "$check" = B ]; then FORCEFIELD=UFF; fi
done

for (( i=1 ; i <= $count ; i++ ))
do
	sed -n "$start","$end"p "$NAME"_conformers.xyz > temp"$i".xyz
	energy=$(obenergy -ff $FORCEFIELD temp"$i".xyz | grep "TOTAL ENERGY" | awk '{print $4}')
	if [ "$FORCEFIELD" = UFF ]; then energy=$(echo "($energy)/4.184" | bc -l | xargs printf "%.*f\n" 2); fi
	sed -i "/$WRS/s/$/ $energy/" temp"$i".xyz
	start=$((start+add))
	end=$((end+add))
done

for (( i=1 ; i <= $count ; i++ ))
do
	en[$i]=$(grep "$WRS" temp"$i".xyz | awk '{print $NF}'); echo $i ${en[$i]} >> "$NAME"-order-values
done
						
sed -i "s/$WRS/9999999/g" "$NAME"-order-values
cat "$NAME"-order-values | sort -n -k2 > "$NAME"-ordered-values; rm "$NAME"-order-values
mkdir "$NAME"-conformers-"$FORCEFIELD"

echo -e "conf\tenergy ("$FORCEFIELD", kcal/mol)" > "$NAME"-list-conformers.txt
for (( i=1 ; i <= $count ; i++ ))
do
	old=$(sed -n "$i"p "$NAME"-ordered-values | awk '{print $1}')
	mv temp"$old".xyz "$NAME"_conf"$i".xyz
								
	energy=$(grep "$WRS" "$NAME"_conf"$i".xyz | awk '{print $NF}')
	echo -e "$i\t$energy" >> "$NAME"-list-conformers.txt

	if [ $i -ne 1 ]; then
		cat "$NAME"_conf"$i".xyz >> "$NAME"_conformers.xyz
	else
		cat "$NAME"_conf"$i".xyz > "$NAME"_conformers.xyz
	fi
																					
	sed -i 1,2d "$NAME"_conf"$i".xyz
	cp "$NAME"_conf"$i".xyz "$NAME"-conformers-"$FORCEFIELD"; rm "$NAME"_conf"$i".xyz
done

cp $WRS "$NAME"-conformers-"$FORCEFIELD"; rm $WRS "$NAME"-ordered-values $FILE
cat "$NAME"-list-conformers.txt
																					 
###### OUTPUT

echo "$count conformer(s) of $FILE were generated."
echo "Find all conformers in "$NAME"-conformers-"$FORCEFIELD" and a list in "$NAME"-list-conformers.txt."
echo "Global energy minimum: "$NAME"_conf1.xyz"
if ! [ -z "$PRINTERROR" ]; then echo "Caution $WRS : $PRINTERROR"; fi
