#!/bin/bash
#
# getInput -i [OUT/XYZ File] -o [template-File] {-d [Directory (Default=Current)] -n [Name] -a 'APPENDIX'}
#

function prepXYZ {
#input: $FILE
#output: $COORDS [raw coordinates]

unset COORDS NEWFILE SUFFIXINPUTFILE
SUFFIXINPUTFILE=$(echo $FILE | rev | cut -f1 -d'.' | rev)
case $SUFFIXINPUTFILE in 
	xyz)
			COORDS=$(cat $FILE)
	;;
	out)	out2xyz $FILE
			NEWFILE=$(echo $FILE | sed 's/.out/.xyz/')
			COORDS=$(cat $NEWFILE); rm $NEWFILE
	;;
	\?) echo "Invalid format."
	;;
esac

CHECKSTART=$(echo "$COORDS" | head -1 | awk '{print NF}')
while [[ $CHECKSTART -ne 4 ]]; do
	COORDS=$(echo "$COORDS" | sed 1d)
	CHECKSTART=$(echo "$COORDS" | head -1 | awk '{print NF}')
done

CHECKEND=$(echo "$COORDS" | tail -1 | awk '{print NF}')
while [[ $CHECKEND -ne 4 ]]; do
	COORDS=$(echo "$COORDS" | sed "$"d)
	CHECKEND=$(echo "$COORDS" | tail -1 | awk '{print NF}')
done

}

unset INPUTFILE OUTPUTFILE APPENDIX NAME
TEMPLATEDIR=~/inputs/
WORKDIR=.
SETDIR=0
while getopts "hi:o:a:n:Dd:" OPTION; do
	case $OPTION in
		h) echo "Help-File does not exist yet."; exit
		;;
		i) INPUTFILE=$OPTARG
			if [ ! -f "$INPUTFILE" ]; then
				echo "Error: $INPUTFILE does not exist."
				exit
			fi
		;;
		o) OUTPUTFILE=$OPTARG
			if [ ! -f "$OUTPUTFILE" ]; then
				CURRDIR=$(pwd);	cd $TEMPLATEDIR; TEMPLATEDIR=$(pwd); cd $CURRDIR
				NEWOUTPUTFILE=$TEMPLATEDIR/$OUTPUTFILE
				if [ ! -f "$NEWOUTPUTFILE" ]; then
					echo "Error: $OUTPUTFILE does not exist."
					exit
				else
					OUTPUTFILE=$NEWOUTPUTFILE
				fi
			fi
			SUFFIXOUTPUTFILE=$(echo $OUTPUTFILE | rev | cut -f1 -d'.' | rev)
		;;
		a) APPENDIX=$OPTARG
		;;
		n) NAME=$OPTARG
		;;
		D) SETDIR=1
		;;
		d) WORKDIR=$OPTARG
			if [ ! -d "$WORKDIR" ]; then mkdir $WORKDIR; SETDIR=0; fi
		;;
	esac
done

if [ -z "$NAME" ]; then
	NAME=$(echo $INPUTFILE | rev | cut -f1 -d'/' | rev | cut -f1 -d'.')
#	SUFFIXOUTPUTFILE=$(echo $OUTPUTFILE | rev | cut -f1 -d'.' | rev)
	NAME=$(echo $NAME.$SUFFIXOUTPUTFILE)
fi

if [ "$SETDIR" = 1 ]; then 
	WORKDIR=$(echo $NAME | cut -f1 -d'.')
	mkdir $WORKDIR
fi

FILE=$INPUTFILE; prepXYZ

if [ ! -f $WORKDIR/$NAME ]; then cp $OUTPUTFILE $WORKDIR/$NAME; else echo "Error: $WORKDIR/$NAME already exists."; exit; fi
echo -e "$COORDS\n" >> $WORKDIR/$NAME
if [[ $SUFFIXOUTPUTFILE = inp ]] ; then ### ORCA FILE
	sed -i "$"d $WORKDIR/$NAME
	echo -e "*\n" >> $WORKDIR/$NAME
fi 
echo -e "$APPENDIX\n" >> $WORKDIR/$NAME


