#!/bin/bash


while getopts "f:" OPTION
do
	case $OPTION in 
	f)
		FILE=$OPTARG
		;;
	*)
		echo -e "Usage of nonexistent flag.\033[31m Aborting.\033[0m"
		exit
		;;
	esac
done


# echo "now starting"

#grep "| " $FILE | grep -m 2 "*" | sed -e 's/>//g' > tmp.txt

# echo "positions for NAtom calc. found"

#begin=`head -1 tmp.txt | awk '{print $2}' `
#end=`tail -1 tmp.txt | awk '{print $2}'`

# echo "numers extracted"

NAtoms=`grep -m 1 "Number of atoms" $FILE | awk '{print $5}'`
NAtomsPlus=` echo "$NAtoms + 5" | bc ` 


COORDS=`tac $FILE | grep  -m 1 -B $NAtomsPlus "FINAL ENERGY EVALUATION AT THE STATIONARY POINT" | tac | sed -e '1,6d' | awk '{print $1 "      " $2 "      " $3  "      "$4}'`

# echo "nur noch schreiben der txt datei"

NEWFILE=`echo $FILE | sed -e s@.out@@g `

echo -e "$NAtoms "> $NEWFILE.xyz
echo -e " " >> $NEWFILE.xyz
echo -e "$COORDS" >> $NEWFILE.xyz


#rm tmp.txt
